### ISSUE TITLE
getting unidentified every time i run

### ISSUE THREAD

**Issue by jcameron-idc** [mwpenny/kijiji-scraper#10]
Hello, I am having a small issue and can't seem to figure out how to solve it,  I follow the setup and such on git readme. but when I run the script, I get undefined. im using it in my angular cli project
```
let kijiji = require("kijiji-scraper");

let prefs = {
    "locationId": 9004,
    "categoryId": 54,
    "scrapeInnerAd":false
};

let params = {
  keywords: "Web" + "designer" + "developer",
  adType: "OFFER"
};

kijiji.query(prefs, params, function(err, ads) {
  console.log(kijiji.parse(ads));
});
```

**Comment by mwpenny** [comment]
Hi there, I noticed a couple of things:

First, the plus signs in the `keywords` property should be within the string. For what I think you're trying to do, the value would be "Web+designer+developer". The way you are doing it concatenates the strings, resulting in "Webdesignerdeveloper".

Second, you are calling `kijiji.parse` on the list of ads, but the function only handles one ad, so you should iterate over the ads and call the function for each one.

Let me know if you're still having problems after that!

**Comment by mwpenny** [comment]
I haven't heard anything back in almost a month so I'm going to assume that his has been resolved. Please let me know if you're still having problems.

For anyone else, @jcameron-idc's code works for me after making my previously mentioned changes. I changed the line

```js
console.log(kijiji.parse(ads));
```
to
```js
ads.forEach(ad => console.log(kijiji.parse(ad)));
```
and used "web+design+developer" for the `keywords` value (since no Kijiji postings matched the original value).
