### ISSUE TITLE
Support location radius for search

### ISSUE THREAD

**Issue by benwiley4000** [mwpenny/kijiji-scraper#16]
Thanks for this great tool!

The kijiji url appears to pack the kilometer radius parameter *before* the query string, e.g. for 3 km radius:

```
https://www.kijiji.ca/b-appartement-condo/ville-de-montreal/1+salle+de+bains-3+1+2/c37l1700281a120a27949001r3.0?...
```

Is there a way to query with a radius currently? Or would the library need to be updated?

**Comment by mwpenny** [comment]
Hi,

Searches on Kijiji are performed via a request to `https://www.kijiji.ca/b-search.html`, then your browser is redirected to an easy-to-share URL that encodes which parameters were used (the URL in your example). So it's confusing because there are two ways to do the search. I chose the former because it was more structured.

For radius, you can specify `radius` in the search params:
```js
var kijiji = require('kijiji-scraper');

let params = {
    locationId: kijiji.locations.QUEBEC.GREATER_MONTREAL.CITY_OF_MONTREAL,
    categoryId: kijiji.categories.REAL_ESTATE.APARTMENTS_AND_CONDOS_FOR_RENT,
    radius: 3
};

kijiji.search(params).then((ads) => {
	// Do whatever you want in here
	ads.forEach(ad => console.log(ad.title));
});
```

Glad you found use in this project!

**Comment by benwiley4000** [comment]
Ah - thank you!
