### ISSUE TITLE
Migration to Typecript

### ISSUE THREAD

**Issue by technoligest** [mwpenny/kijiji-scraper#27]
Hi! Would you like me to work on migrating the code to Typescript? I think that would help in improving the interface for users and will make it easier to add tests and extend the project in the future. It will be substantial work so I wanted to check with you before working on it and raising a pr.

**Comment by mwpenny** [comment]
Hi, I'd be open to that. Typescript is great and I agree with your points.

Due to the amount of work, I suggest doing it in two parts: first just add the type definitions for the public interface, then transition the library to TypeScript.

The first pass doesn't have to use tons of TS features, I see it as being an iterative process.

**Comment by mwpenny** [comment]
If you're worried about one massive PR, it is probably worth doing it in a few passes

**Comment by mwpenny** [comment]
Heads up: due to inactivity I've added type definitions and plan to migrate the codebase to TypeScript. It's in its own branch right now while still in progress (`typescript-refactor`).

**Comment by mwpenny** [comment]
I'm also adding unit tests as part of this

**Comment by mwpenny** [comment]
The module is now written in TypeScript (#38) :)
