### ISSUE TITLE
Search() with URL

### ISSUE THREAD

**Issue by DudeManGuy0** [mwpenny/kijiji-scraper#43]
A good feature would be making Search() be able to take in a query URL over specifying parameters for more convenience. This also helps with Kijiji's relative location filter which takes your location and applies a radius to search in.

**Comment by mwpenny** [comment]
I see - so you'd perform your search on Kijiji, configure everything you want, and then just use that URL with this module?

That would be nice but it wouldn't work with the mobile API-based scraping (default) since 1) the URLs are completely different and 2) the query string parameter names in the URL don't all match up with the API parameter names, so there would have to be a hard-coded mapping from one set of parameter names to another which breaks down if Kijiji ever adds, removes, or changes parameters.

It's also already possible to use the location filtering with the module's current API:

```js
const kijiji = require("kijiji-scraper");

const params = {
    locationId: kijiji.locations.QUEBEC.GREATER_MONTREAL.CITY_OF_MONTREAL,
    categoryId: kijiji.categories.REAL_ESTATE.APARTMENTS_AND_CONDOS_FOR_RENT,
    distance: 3  // Kilometers
};

kijiji.search(params);
```

You can specify the base location using the `zipcode` (works with postal code), `address`, or `longitude`/`latitude` parameters. By default it just uses whatever location you specify for `locationId`. Note that this is for API scraping. For HTML, use `radius` instead of `distance`. If you're using HTML scraping, you can find other parameters by inspecting the HTTP request when searching (look for the request to `b-search.html`).

So for these reasons I'm going to close this. The goal of the module is to abstract away the underlying API and provide a way to query it programmatically - agnostic of how Kijiji does things on their end. This approach is what allowed easy integration of the mobile API backend alongside the HTML one.

If there's a search that you can do on Kijiji that you can't do with this module, please open another issue.
