### ISSUE TITLE
Consideration for expanding repo to Kijiji API

### ISSUE THREAD

**Issue by DudeManGuy0** [mwpenny/kijiji-scraper#52]
Let me know what you think of the idea of expanding this repo to be a full Kijiji API. I understand if It might be too much work or out of the scope of this project, but let me know if you would open to the idea of me writing some functions like methods for posting ads.
This also possibly has the opportunity of turning Kijiji into a platform full of bots. But anyone can write code so why hasn't a private repo already be made to do that? Who knows, just leave it up for consideration and I can start writing methods for stuff like that. If the answer is yes, some documentation or a basic breakdown of how the codebase works would be cool because I personally cannot understand any of it.
It might make the repo better but if there is no need for it then there is no reason. Personally I just wanted to make a function to post ads but saw it was probably out of the scope of this project. Let me know your thoughts.

**Comment by mwpenny** [comment]
Hi there, I appreciate the offer but the goal of this project is to do one thing well, rather than trying to do everything - that one thing being retrieving information about Kijiji ads. So posting ads is outside of the scope of this project. I'd like the scope to remain modest like this in order to keep the module more maintainable and also easier to use in other projects.

I found a few other projects which support posting ads and may suit your needs:
* https://github.com/adrienverge/kijijiapi (looks abandoned)
* https://github.com/ArthurG/Kijiji-Repost-Headless (last updated a few months ago)
* https://github.com/rybodiddly/Kijiji-Reposter (last updated a few months ago)

You're also of course free to fork this repository and add whichever features you want to your own version. `lib/backends/api-scraper.ts` and `lib/backends/api-searcher.ts` are where I interact with the mobile API, and some of the tests have code to generate example API responses (it is XML-based). Those would be good places to start.

As for bots, I guarantee many people have written bots to post ads for commercial purposes but they probably want to keep it to themselves 😛
