### ISSUE TITLE
Scraper fails to properly scrape some numeric attributes (real numbers)

### ISSUE THREAD

**Issue by keery** [mwpenny/kijiji-scraper#55]
Hello,

I noticed that when you fetch apartment ads, the attributes **numberbathrooms** value is always equal to **10**.

Have nice day

**Comment by mwpenny** [comment]
Hi there. I did some poking around and what's actually happening is that the number of bathrooms is being multiplied by 10 in order to support "half" bathrooms without needing to store a floating point value internally.

For example:
* For https://www.kijiji.ca/v-apartments-condos/ottawa/silver-court-apartments:-apartment-for-rent-in-experimental/1557657830, the number of bathrooms displayed is `1` but it gets scraped as `10`
* For https://www.kijiji.ca/v-apartments-condos/ottawa/2m-from-uottawa-private-bathroom-417-nelson-room-in-a-3bedroom/1549448108, the number of bathrooms displayed is `3` but it gets scraped as `30`
* For https://www.kijiji.ca/v-apartments-condos/ottawa/two-bedroom-maisonettes-skyline-for-rent-30-eleanor-drive/1550310250, the number of bathrooms displayed is `1.5` but it gets scraped as `15`.

For each attribute, Kijiji stores an internal value and locale-specific values. These internal values are used for filtering and searching but when you view the ad in a browser or the mobile app, the UI will display the locale-specific value. In this case, the internal value has been multiplied by 10 and the locale-specific value is the expected one. Kijiji does it this way so the way things are displayed is flexible (e.g., they can display `1 1/2` instead of `1.5`. Why they don't store the internal value as floating point is anyone's guess. It probably makes it easier to do database lookups behind the scenes. The scraper only reads the internal value, which explains why you're seeing this behavior.

For consistency, I want to use the internal value wherever possible. So what I will do is use the English locale-specific value if and only if:
1. The internal value is a number, and
2. The English locale-specific value is also a number

This should address your use case (and others like it which may come up) while also not changing things too much. I've tested locally with the ads mentioned above and the bathrooms are reported correctly.

I also found that boolean values aren't scraped correctly when using the mobile API, so I've fixed that as well. See the linked commits for both changes.

**Comment by mwpenny** [comment]
The latest version (6.1.3) is now on NPM. Please give it a try.

**Comment by keery** [comment]
Thank you a lot for this explanation, it makes more sense now, I am trying the latest version.
One more question, I noticed that for a renting ad like apartment, there isn't the total numbers of rooms, we got bedroom number and bathroom number, but not the total like this
![image](https://user-images.githubusercontent.com/10221598/113482259-1439ad80-949e-11eb-936c-daf6ff80097b.png)

How do you solve that ? The sum of bathroom + bedroom ?

**Comment by mwpenny** [comment]
Today I learned about [French real estate terminology](https://www.angloinfo.com/how-to/france/housing/property-jargon). 😛 

You probably know this since your profile says you're in Paris, but I didn't and other English people may see this: In French real estate listings, the convention is to list the number of pièces/rooms rather than number of bedrooms. This number includes all "living areas" such as the dining room, living room, and bedrooms and excludes other rooms like the kitchen and bathrooms. So `numberbedrooms + numberbathrooms != pièces`.

On Kijiji, the internal value and English locale-specific value that they use for the `numberbedrooms` attribute are both the same (equal to the actual number of bedrooms) but the French locale-specific value refers to the number of pièces/rooms.

However, for simplicity they don't actually differentiate between these two concepts internally. When I go to create an ad with my language set to French, sure enough I see a dropdown for pièces rather than chambres.
![image](https://user-images.githubusercontent.com/9356790/113947093-e58e4080-97d7-11eb-89ac-671d64833eb0.png)

But looking at the HTML, they just have a hard-coded mapping from number of bedrooms to number of pièces (in fact, the element's ID is still `numberbedrooms_s`). This is likely so that regardless of the language used when creating the ad there will still be a value that makes sense in both English and French - posters don't need to specify both bedroom count and room count. This explains what's happening with the `numberbedrooms` attribute.
![image](https://user-images.githubusercontent.com/9356790/113947743-541fce00-97d9-11eb-9e51-7a3a21ff528c.png)

So if you want to convert from `numberbedrooms` to pièces in your code, you can use the mapping in the screenshot above. Basically, 0 bedrooms means it's a bachelor/studio, otherwise `pièces = Math.floor(numberbedrooms) + 2.5`. And a `numberbedrooms` ending in `.5` indicates that there is a den. The `2.5` constant in the formula is some base number of rooms Kijiji has decided upon, but I'm not sure how they arrived at that number. Maybe living room (1) + dining area (1) + entrance (0.5)?

Hope that helps.

**Comment by keery** [comment]
Ahaha glad to make you discover new things, more specifically this system like 1 1/2, 2 1/2 is only in Quebec, in France it's another system based on number of rooms and meters square.

I checked on Kijiji what you explained me and I will able to convert this really easily with this mapping. Your explanation helps me a lot, thanks a lot

**Comment by mwpenny** [comment]
Ah, interesting. Another difference in Canadian French haha. There's another property called `areainfeet` by the way, which will give you square footage. However not all ads have it set (it will be 0 sometimes).

I'm going to close this issue now that the original bug and your question have been resolved. Feel free to open another issue if you run into problems again.

All the best with your project!
