### ISSUE TITLE
Incorrect Size Attribute For Shoe Category

### ISSUE THREAD

**Issue by Arjun-Sharma1** [mwpenny/kijiji-scraper#61]
The size attribute is set as a date instead of a shoe size when scraping data from the `Clothing -> Shoe` category. I am using the "html" option for Ad.get(). The size attribute seems to work fine when using the default mobile api but doesn't work with the html option. 

Here is a picture of the incorrect scraped result for the shoe size. 
https://i.gyazo.com/2992bb9d6e5a9ed2f30f4cf2a6fed47b.png

**Comment by mwpenny** [comment]
Hi there. Could you please provide a URL for an ad that can reproduces this issue? Thanks!

**Comment by Arjun-Sharma1** [comment]
Sure this is a random one I tried and produced the issue.

https://www.kijiji.ca/v-mens-shoes/mississauga-peel-region/jordan-12-retro-indigo/1564240827 and here's another
https://www.kijiji.ca/v-mens-shoes/mississauga-peel-region/nike-air-vapormax-360-grey/1564281977

This is what the correct size attribute should show ( Used "api" as the scraper type ): 
https://gyazo.com/1c1b153315c43f5066479b97c5a70aec

**Comment by Arjun-Sharma1** [comment]
Apparently, this happens for any category that has the size attribute (Clothing)

**Comment by mwpenny** [comment]
Kijiji sends all ad attributes as strings. The mobile API also sends type information, but unfortunately the HTML site doesn't. So for each ad attribute, the HTML scraper tries to determine the type with various checks and then cast the value accordingly. If all checks fail then the value is treated as a string.

What we're seeing here is a false positive due to V8's date parsing being very permissive. The `Date` constructor and `Date.parse()` appear to ignore characters at the beginning of a date string if they're followed by one of a handful of delimiters (` `, `.`, `-`, and possibly more) and then a valid date string. For example, `new Date("blah-2021-05-05T23:36:25.833Z")` returns a valid `Date` when run in Chrome or Node.js. The same date string is invalid in Firefox (SpiderMonkey). This is in line with the [language spec](https://tc39.es/ecma262/#sec-date.parse):
> In general, the value produced by Date.parse is implementation-defined when given any String value that does not conform to the Date Time String Format (21.4.1.15) [simplified ISO 8601] and that could not be produced in that implementation by the toString or toUTCString method.

Due to this behavior, and since `new Date("10")` is a valid (implementation-specific) date in V8, `new Date("size-10")` is also valid and the size string is interpreted as a date by the scraper.

From what I've seen, Kijiji always uses ISO date strings. They're not exactly equal to JS-style date strings (sometimes have more precision on the time portion), so I'll just change the check to require that date attributes begin with a number.

Good find!

**Comment by mwpenny** [comment]
The latest version on NPM has the fix. Please give it a try.

**Comment by Arjun-Sharma1** [comment]
Thanks for the update! Works great.
